# nfs1 ansible_host=172.31.90.36 ansible_connection=ssh ansible_user=ec2-user
# web1 ansible_host=172.31.84.138 ansible_connection=ssh ansible_user=ec2-user
# web2 ansible_host=172.31.84.232 ansible_connection=ssh ansible_user=ec2-user
# db1 ansible_host=172.31.93.2 ansible_connection=ssh ansible_user=ec2-user
# lb1 ansible_host=172.31.91.52 ansible_connection=ssh ansible_user=ubuntu